"""empty message

Revision ID: 800e0d51ea01
Revises: 8b912e8f7619
Create Date: 2018-11-23 09:37:34.880766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800e0d51ea01'
down_revision = '8b912e8f7619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('like_num', sa.Integer(), nullable=True),
    sa.Column('share_num', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('publish_time', sa.String(length=256), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=40), nullable=True),
    sa.Column('app_fu_title', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('wheel',
    sa.Column('bannerid', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('bannerid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wheel')
    op.drop_table('movies')
    # ### end Alembic commands ###
