"""empty message

Revision ID: b78cda349e4d
Revises: 3b6ec76c7a20
Create Date: 2018-11-23 10:01:29.908371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78cda349e4d'
down_revision = '3b6ec76c7a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('request_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'request_url')
    # ### end Alembic commands ###
